#!/bin/sh

###
# Tools/Git Hooks/.noallow-listファイルに記載されているファイルをコミットしようとするとエラーを出す。
# リストファイルは最後に空行を入れること
#

SELFPATH=${0%/*}

while read LINE
do
  RESULT=`git diff --cached --name-only | grep "$LINE"`
  
  if test -n "${RESULT}"
  then
    echo "${RESULT} do not allow commit."
    exit -1
  fi
done < "${SELFPATH}/../../Tools/Git Hooks/.noallow-list"

# for check.
#exit -1